#%RAML 0.8
---
title: OD-FIP Rates and Prices
version: v1
baseUri: api.transparency.treasury.gov
protocols: [ HTTPS ]

/fiscal_service/v1/accounting/od/fip_rates_prices:
  description: OD-FIP Rates and Prices
  get:
    queryParameters:
      fields:
        displayName: Field List
        type: string
        description: Field parameter accepts a comma separated list of field names that the user wants to be returned in the response.
        example: fields=xxx,yyy,zzz
        required: false
        default: 
      filter:
        displayName: Filter
        type: string
        description: Filter is used to apply logic criteria to each field if necessary (lt, gt, lte, gte, eq, in).
        example: 1) filter=xxx:eq:value,yyy:lt:1,zzz:gt:10  2) filter=reporting_fiscal_year:in:(2007,2008,2009,2010)
        required: false
        default: 
      sort:
        displayName: Sorting
        type: string
        description: Sorting parameter accepts a comma separated list of field names that the user wants to sort the response by.
        example: sort=xxx,-yyy,zzz
        required: false
        default: 
      pretty_print:
        displayName: Pretty Print
        type: string
        description: Pretty print will put carriage returns and indentation in the json response so that it can be easily read by a human.
        example: pretty_print=yes
        required: false
        default: no
      format:
        displayName: Response Format
        type: string
        description: Format is used to define how output method for the response (json, xml, csv).
        example: format=json
        required: false
        default: json
      limit:
        displayName: Row Limit
        type: number
        description: Limit will set the number of rows that are returned in a request.
        example: limit=100
        required: false
        default: 100
      offset:
        displayName: Row Offset
        type: number
        description: Offset will set the starting point of the pagination.
        example: offset=0
        required: false
        default: 0
    responses:
      200:
        body:
          application/xml:
          application/csv:
          application/json:
            schema: |
              {
                "type": "object",
                "$schema": "http://json-schema.org/draft-03/schema",
                "id": "http://jsonschema.net",
                "properties": {
                  "reporting_calendar_day": {
                    "type": "day",
                    "description": "Calendar Day Number",
                    "format": "DD"
                  },
                  "data_date": {
                    "type": "date",
                    "description": "Data Date",
                    "format": "YYYY-MM-DD"
                  },
                  "security_type": {
                    "type": "string",
                    "description": "Security Type",
                    "format": ""
                  },
                  "rate_amt": {
                    "type": "number",
                    "description": "Rate Amount",
                    "format": "10.2"
                  },
                  "maturity_dt": {
                    "type": "date",
                    "description": "Maturity Date",
                    "format": "YYYY-MM-DD"
                  },
                  "call_dt": {
                    "type": "date",
                    "description": "Call Date",
                    "format": "YYYY-MM-DD"
                  },
                  "buy_amt": {
                    "type": "number",
                    "description": "Buy Amount",
                    "format": "10.2"
                  },
                  "sell_amt": {
                    "type": "number",
                    "description": "Sell Amount",
                    "format": "10.2"
                  },
                  "end_of_day_amt": {
                    "type": "number",
                    "description": "End of Day Amount",
                    "format": "10.2"
                  },
                  "cusip": {
                    "type": "string",
                    "description": "CUSIP",
                    "format": ""
                  },
                  "reporting_calendar_year": {
                    "type": "year",
                    "description": "Calendar Year",
                    "format": "YYYY"
                  },
                  "reporting_calendar_month": {
                    "type": "month",
                    "description": "Calendar Month Number",
                    "format": "MM"
                  }
                }
              }
      400:
        body:
          application/json:
            example: |
              {"error":"Invalid Query Param","message":"Invalid query parameter 'foo' with value '[error]'.  For more information please see the documentation."}